{% set name = "machomachomangler" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/machomachomangler-{{ version }}.tar.gz
  sha256: 2acbad5bd465c5f386e5ceac8a8a1939a9789f503dd84f491e046292cf6e54a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - attrs

test:
  imports:
    - machomachomangler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/njsmith/machomachomangler
  summary: Tools for mangling Mach-O and PE binaries
  license: AGPL-3.0-or-later
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
